export enum PropertyType {
  APARTMENT = 'APARTMENT',
  MAISONETTE = 'MAISONETTE',
  DETACHED_HOUSE = 'DETACHED_HOUSE',
  BUILDING = 'BUILDING',
  PENTHOUSE = 'PENTHOUSE',
  FULL_FLOOR_APARTMENT = 'FULL_FLOOR_APARTMENT',
}
